services:
  db:
    image: postgres:14-alpine
    container_name: transactionsdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactionsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      DB_HOST: db
#      DB_USER: user
#      DB_PASSWORD: password
#      DB_NAME: mydb

volumes:
  db_data: